### ISSUE TITLE
Exercice

### ISSUE THREAD

**Issue by flon78** [fbertran/ModStatR#1]
All the code and results for exercices refer to chapter 1 , nothing for the chapters 2,3,4.

please, correct this.

**Comment by fbertran** [comment]
The links are incorrect but the files are online. You can access to the solutions to chapter 2 to 4 by following those links:
https://fbertran.github.io/ModStatR/articles/SolChapitre2.html
https://fbertran.github.io/ModStatR/articles/SolChapitre3.html
https://fbertran.github.io/ModStatR/articles/SolChapitre4.html

**Comment by flon78** [comment]
thank you


De : Frederic Bertrand ***@***.***>
À : fbertran/ModStatR ***@***.***>
Sujet : Re: [fbertran/ModStatR] Exercice (Issue #1)
Date : 08/03/2024 14:46:32 Europe/Paris
Copie à : flon78 ***@***.***>;
   Author ***@***.***>


The links are incorrect but the files are online. You can access to the solutions to chapter 2 to 4 by following those links:
https://fbertran.github.io/ModStatR/articles/SolChapitre2.html
https://fbertran.github.io/ModStatR/articles/SolChapitre3.html
https://fbertran.github.io/ModStatR/articles/SolChapitre4.html

**Comment by fbertran** [comment]
The links should be fixed now.
